/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taskmanagmentsystemfinal;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author HP
 */
public class CreateTask extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public CreateTask() {
        initComponents();
        creatorname.setText(alog.getUsern());
        
        ID();
        employee();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        code = new javax.swing.JTextField();
        title = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        description = new javax.swing.JTextField();
        phase = new javax.swing.JTextField();
        priority = new javax.swing.JTextField();
        creatorname = new javax.swing.JTextField();
        estimation = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        Project_ID = new javax.swing.JComboBox<>();
        assignedfor = new javax.swing.JComboBox<>();
        year1 = new javax.swing.JComboBox<>();
        day1 = new javax.swing.JComboBox<>();
        m1 = new javax.swing.JComboBox<>();
        day2 = new javax.swing.JComboBox<>();
        m2 = new javax.swing.JComboBox<>();
        year2 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setText("Code");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setText("Title");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setText("Description");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setText("Assigned For ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel5.setText("Phase");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));
        getContentPane().add(code, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 179, -1));
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 179, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel6.setText("Estimation hours");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setText("Priority");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel8.setText("Creator Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel9.setText("Start");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel10.setText("End");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 40, -1));

        jLabel11.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel11.setText("Project ID");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionActionPerformed(evt);
            }
        });
        getContentPane().add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 320, 40));

        phase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phaseActionPerformed(evt);
            }
        });
        getContentPane().add(phase, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 179, -1));

        priority.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priorityActionPerformed(evt);
            }
        });
        getContentPane().add(priority, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 179, -1));

        creatorname.setEditable(false);
        creatorname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creatornameActionPerformed(evt);
            }
        });
        getContentPane().add(creatorname, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 179, -1));
        getContentPane().add(estimation, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, 179, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 190, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jLabel12.setFont(new java.awt.Font("Georgia", 1, 48)); // NOI18N
        jLabel12.setText("Create task");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 300, -1));

        getContentPane().add(Project_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 180, -1));

        getContentPane().add(assignedfor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 180, -1));

        year1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023", "2024", "2025" }));
        getContentPane().add(year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 230, 60, -1));

        day1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        day1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day1ActionPerformed(evt);
            }
        });
        getContentPane().add(day1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 230, 60, -1));

        m1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        getContentPane().add(m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 60, -1));

        day2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        getContentPane().add(day2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 60, -1));

        m2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        getContentPane().add(m2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 60, -1));

        year2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023", "2024", "2025", " " }));
        getContentPane().add(year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 260, 60, -1));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 930, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void priorityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priorityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priorityActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            String code1 = code.getText();
            String title1 = title.getText();
            String description1 = description.getText();
            String assignedfor1 = assignedfor.getSelectedItem().toString();
            String phase1 = phase.getText();
            String projectid1 = Project_ID.getSelectedItem().toString();
            String priority1 = priority.getText();
            String creatorname1 = creatorname.getText();
            String start1 = day1.getSelectedItem().toString() + "/" + m1.getSelectedItem().toString() + "/" + year1.getSelectedItem().toString();
            String end1 = day2.getSelectedItem().toString() + "/" + m2.getSelectedItem().toString() + "/" + year2.getSelectedItem().toString();
            String estimation1 = estimation.getText();

            if (!code1.isEmpty() && !title1.isEmpty() && !description1.isEmpty() && !assignedfor1.isEmpty()
                    && !phase1.isEmpty() && !projectid1.isEmpty() && !priority1.isEmpty() && !creatorname1.isEmpty()
                    && !estimation1.isEmpty()) {
                Database db = new Database();
                if (db.CreateTask(code1, title1, description1, assignedfor1, phase1, projectid1, priority1, creatorname1, start1, end1, estimation1)) {
                    JOptionPane.showMessageDialog(null, "inserted");
                    backPress();
                } else {
                    JOptionPane.showMessageDialog(null, "error");
                }
            } else {
                JOptionPane.showMessageDialog(null, "You must enter all fields");
            }

        } catch (Exception e) {
            System.out.println("SQL Exception: " + e.toString());

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionActionPerformed

    private void creatornameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creatornameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creatornameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        backPress();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void phaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phaseActionPerformed

    private void day1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_day1ActionPerformed
    private void backPress() {
        taskupdate_create y = new taskupdate_create();
        y.setVisible(true);
        this.setVisible(false);
    }

    private void ID() {
        try {
            ResultSet rs;
            DatabaseFunction db = new DatabaseFunction();
            Connection con = db.getconnection();
            String s = "select * from projects";
            rs = db.combobox(s);
            while (rs.next()) {
                Project_ID.addItem(rs.getString("project_id"));
            }
        } catch (Exception e) {
            System.out.println("SQL Exception: " + e.toString());

        }
    }

    private void employee() {
        try {
            ResultSet rs;
            DatabaseFunction db = new DatabaseFunction();
            Connection con = db.getconnection();
            String s = "select * from employee";
            rs = db.combobox(s);
            while (rs.next()) {
                assignedfor.addItem(rs.getString("username"));
            }
        } catch (Exception e) {
            System.out.println("SQL Exception: " + e.toString());

        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateTask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Project_ID;
    private javax.swing.JComboBox<String> assignedfor;
    private javax.swing.JTextField code;
    private javax.swing.JTextField creatorname;
    private javax.swing.JComboBox<String> day1;
    private javax.swing.JComboBox<String> day2;
    private javax.swing.JTextField description;
    private javax.swing.JTextField estimation;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> m1;
    private javax.swing.JComboBox<String> m2;
    private javax.swing.JTextField phase;
    private javax.swing.JTextField priority;
    private javax.swing.JTextField title;
    private javax.swing.JComboBox<String> year1;
    private javax.swing.JComboBox<String> year2;
    // End of variables declaration//GEN-END:variables
}
