/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taskmanagmentsystemfinal;


import java.sql.Connection;
import java.sql.ResultSet;

import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class UpdateTask extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public UpdateTask() {
        initComponents();
         creator.setText(alog.getUsern());
        
        employee();
        tasks();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        description = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        phase = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        priority = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        creator = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        estimation = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        employee = new javax.swing.JComboBox<>();
        code = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        day1 = new javax.swing.JComboBox<>();
        m1 = new javax.swing.JComboBox<>();
        year1 = new javax.swing.JComboBox<>();
        year2 = new javax.swing.JComboBox<>();
        m2 = new javax.swing.JComboBox<>();
        day2 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setText("title");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleActionPerformed(evt);
            }
        });
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 179, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setText("Description");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, -1, -1));

        description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionActionPerformed(evt);
            }
        });
        getContentPane().add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 220, 40));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setText("Assigned for");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setText("Phase");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        phase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phaseActionPerformed(evt);
            }
        });
        getContentPane().add(phase, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 179, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel5.setText("Priority");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));
        getContentPane().add(priority, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 179, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel6.setText("Creator");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, -1, -1));

        creator.setEditable(false);
        creator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creatorActionPerformed(evt);
            }
        });
        getContentPane().add(creator, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 179, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setText("Start");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel8.setText("End");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, -1, -1));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel9.setText("Estimation hour ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, -1, -1));

        estimation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estimationActionPerformed(evt);
            }
        });
        getContentPane().add(estimation, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 179, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 190, 40));

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel10.setText("code");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 90, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Display");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 190, 40));

        jLabel11.setFont(new java.awt.Font("Georgia", 1, 48)); // NOI18N
        jLabel11.setText("Update task");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 330, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        getContentPane().add(employee, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 180, -1));

        getContentPane().add(code, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 300, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 300, -1));

        day1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        day1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day1ActionPerformed(evt);
            }
        });
        getContentPane().add(day1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 60, -1));

        m1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        getContentPane().add(m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 60, -1));

        year1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023", "2024", "2025" }));
        getContentPane().add(year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 60, -1));

        year2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023", "2024", "2025", " " }));
        getContentPane().add(year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, 60, -1));

        m2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        getContentPane().add(m2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 60, -1));

        day2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        getContentPane().add(day2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, 60, -1));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 930, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleActionPerformed

    private void descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionActionPerformed

    private void phaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phaseActionPerformed

    private void estimationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estimationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estimationActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String code1=code.getSelectedItem().toString();
        
                   String title1=title.getText();
                   String description1=description.getText();
                   String assignedfor1=employee.getSelectedItem().toString();
                   String phase1=phase.getText();
                   String priority1=priority.getText();
                   String creatorname1=creator.getText();
                  String start1=day1.getSelectedItem().toString()+"/"+m1.getSelectedItem().toString()+"/"+year1.getSelectedItem().toString();
                  String end1=day2.getSelectedItem().toString()+"/"+m2.getSelectedItem().toString()+"/"+year2.getSelectedItem().toString();
                   String estimation1=estimation.getText();
                  
                  if (!code1.isEmpty() && !title1.isEmpty() && !description1.isEmpty() && !assignedfor1.isEmpty()
                && !phase1.isEmpty() && !priority1.isEmpty() && !creatorname1.isEmpty()
                && !estimation1.isEmpty()) {
                Database db = new Database();
                if(db.UpdateTask(code1, title1, description1, assignedfor1, phase1, priority1, creatorname1, start1, end1, estimation1))
                {JOptionPane.showMessageDialog(null,"data updated"); 
                backPress();
                
                }
                else
                     JOptionPane.showMessageDialog(null,"invalid task");  
            }
                     else
                     JOptionPane.showMessageDialog(null,"You must enter all feilds");
                                           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void creatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creatorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creatorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       backPress();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void day1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_day1ActionPerformed

   private void backPress()
    {
           taskupdate_create y=new taskupdate_create();
        y.setVisible(true);
        this.setVisible(false);
    }
   private void employee() 
    {try {
           ResultSet rs;
          DatabaseFunction db = new DatabaseFunction();
            Connection con = db.getconnection();
          String s = "select * from employee";
         rs=db.combobox(s);
        while(rs.next())
        {
            employee.addItem(rs.getString("username"));
        }
         } catch (Exception e) {
            System.out.println("SQL Exception: " + e.toString());
          
        }
    }
   private void tasks()
    {try {
           ResultSet rs;
          DatabaseFunction db = new DatabaseFunction();
            Connection con = db.getconnection();
          String s = "select * from tasks";
         rs=db.combobox(s);
        while(rs.next())
        {
            code.addItem(rs.getString("code"));
        }
         } catch (Exception e) {
            System.out.println("SQL Exception: " + e.toString());
          
        }
    }

   
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateTask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> code;
    private javax.swing.JTextField creator;
    private javax.swing.JComboBox<String> day1;
    private javax.swing.JComboBox<String> day2;
    private javax.swing.JTextField description;
    private javax.swing.JComboBox<String> employee;
    private javax.swing.JTextField estimation;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> m1;
    private javax.swing.JComboBox<String> m2;
    private javax.swing.JTextField phase;
    private javax.swing.JTextField priority;
    private javax.swing.JTextField title;
    private javax.swing.JComboBox<String> year1;
    private javax.swing.JComboBox<String> year2;
    // End of variables declaration//GEN-END:variables
}
