/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taskmanagmentsystemfinal;


import java.sql.Connection;
import java.sql.ResultSet;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class updateuser extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public updateuser() {
        initComponents();
      
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        passwordxx = new javax.swing.JTextField();
        radioLeader = new javax.swing.JRadioButton();
        radioEmployee = new javax.swing.JRadioButton();
        radioAdmin = new javax.swing.JRadioButton();
        update = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        users = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setText("Username");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login.setText("Display");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 190, 40));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel5.setText("password");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));

        passwordxx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordxxActionPerformed(evt);
            }
        });
        jPanel1.add(passwordxx, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 219, -1));

        buttonGroup1.add(radioLeader);
        radioLeader.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        radioLeader.setText("Leader");
        radioLeader.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(radioLeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 93, -1));

        buttonGroup1.add(radioEmployee);
        radioEmployee.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        radioEmployee.setText("Employee");
        radioEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(radioEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 130, -1));

        buttonGroup1.add(radioAdmin);
        radioAdmin.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        radioAdmin.setText("Admin");
        radioAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(radioAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 93, -1));

        update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 190, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setText("Role");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, -1, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 48)); // NOI18N
        jLabel6.setText("Update user");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 330, -1));

        users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersActionPerformed(evt);
            }
        });
        jPanel1.add(users, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 220, -1));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 930, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try
        {
            String username =users.getText();
            String password = passwordxx.getText();
            String role = "";
            
            if(radioAdmin.isSelected())
                role = "A";
            else
                if(radioEmployee.isSelected())
                    role = "E";
                else
                    if(radioLeader.isSelected())
                        role = "L";

            if(!password.isEmpty() && !role.isEmpty())
            {
                Database db = new Database();
                if(db.UpdateUser(username,password,role))
                {
                    JOptionPane.showMessageDialog(null,"data updated"); 
                  backPress();
                }
                else
                    JOptionPane.showMessageDialog(null,"Error");  


            }
           
        }
        catch(Exception ex)
        {
            System.out.println("SQL Exception: "+ ex.toString());
        }

    }//GEN-LAST:event_updateActionPerformed

    private void passwordxxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordxxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordxxActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:

        try {

            String username =users.getText();

            Database db = new Database();
            ResultSet result = db.LoginWithUser(username);

            if(result != null)
            {
                if(result.next())
                {
                    users.setEnabled(false);
                    String password =result.getString(2);
                    String role = result.getString(3);

                    switch (role) {
                        case "A":
                        radioAdmin.setSelected(true);

                        break;
                        case "E":
                        radioEmployee.setSelected(true);

                        break;
                        case "L":
                        radioLeader.setSelected(true);

                        break;

                    }

                    passwordxx.setText(password);

                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Invalid Username");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Invalid Username");
            }

        } catch (Exception e) {
            System.out.println(" Exception: "+ e.toString());
        }
    }//GEN-LAST:event_loginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      backPress();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usersActionPerformed

   private void backPress()
    {
         user     user  = new    user();
         user .setVisible(true);
        this.setVisible(false);
    }
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateuser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JTextField passwordxx;
    private javax.swing.JRadioButton radioAdmin;
    private javax.swing.JRadioButton radioEmployee;
    private javax.swing.JRadioButton radioLeader;
    private javax.swing.JButton update;
    private javax.swing.JTextField users;
    // End of variables declaration//GEN-END:variables
}
